<?php
if(!defined('B_PROLOG_INCLUDED') || B_PROLOG_INCLUDED !== true) die();

use Bitrix\Main\Localization\Loc;

return [
    '_INCLUDE' => ['CONTENT_TABS'],
    'NAME' => Loc::getMessage('RX_BLOCK_17_1_NAME'),
    'INDENT_TOP_DEFAULT' => 100,
    'INDENT_BOT_DEFAULT' => 100,
    'TITLE_POSITION' => 'center',
    'TITLE_SHOW_BTN' => false,
    'TITLE_SHOW_DESC' => false,
    'CLASSES' => 'loading',
    'ELEMENTS_FIELDS' => [
        'NAME',
        'PREVIEW_TEXT',
        'PREVIEW_PICTURE',
        'PROPERTY_MARKERS',
        'PROPERTY_CHARS',
        '_PRICE',
        '_BTN',
    ],
    'DEMO' => [
        'BLOCK' => [
            'NAME' => Loc::getMessage('RX_BLOCK_17_1_DEMO_BLOCK_NAME'),
            'PROPERTY_VALUES' => [
                'USE_TABS' => 'Y',
            ]
        ],
        'TABS' => [
            Loc::getMessage('RX_BLOCK_17_1_DEMO_TAB_1'),
            Loc::getMessage('RX_BLOCK_17_1_DEMO_TAB_2'),
            Loc::getMessage('RX_BLOCK_17_1_DEMO_TAB_3'),
            Loc::getMessage('RX_BLOCK_17_1_DEMO_TAB_4'),
        ],
        'ELEMENTS' => [
            [
                'NAME' => 'Year+',
                'PREVIEW_PICTURE' => '1.png',
                'PREVIEW_TEXT' => Loc::getMessage('RX_BLOCK_17_1_DEMO_ELEMENT_PREVIEW_TEXT'),
                'PREVIEW_TEXT_TYPE' => 'html',
                'TAB' => 0,
                'PROPERTY_VALUES' => [
                    'CHARS' => [
                        Loc::getMessage('RX_BLOCK_17_1_DEMO_ELEMENT_CHARS_1'),
                        Loc::getMessage('RX_BLOCK_17_1_DEMO_ELEMENT_CHARS_2'),
                        Loc::getMessage('RX_BLOCK_17_1_DEMO_ELEMENT_CHARS_3'),
                    ],
                    'PRICE' => '1000',
                    'BTN_SHOW' => 'Y',
                    'BTN_TYPE' => 'btn-transparent',
                    'BTN_SIZE' => false,
                    'BTN_TEXT' => Loc::getMessage('RX_BLOCK_17_1_DEMO_ELEMENT_BTN_TEXT'),
                    'BTN_LINK' => 'ranx_landing_form_order',
                    'BTN_LINK_TYPE' => 'form',
                ],
            ],
            [
                'NAME' => 'Year+',
                'PREVIEW_PICTURE' => '1.png',
                'PREVIEW_TEXT' => Loc::getMessage('RX_BLOCK_17_1_DEMO_ELEMENT_PREVIEW_TEXT'),
                'PREVIEW_TEXT_TYPE' => 'html',
                'TAB' => 1,
                'PROPERTY_VALUES' => [
                    'CHARS' => [
                        Loc::getMessage('RX_BLOCK_17_1_DEMO_ELEMENT_CHARS_1'),
                        Loc::getMessage('RX_BLOCK_17_1_DEMO_ELEMENT_CHARS_2'),
                        Loc::getMessage('RX_BLOCK_17_1_DEMO_ELEMENT_CHARS_3'),
                    ],
                    'PRICE' => '3000',
                    'DISCOUNT_PRICE' => '500',
                    'BTN_SHOW' => 'Y',
                    'BTN_TYPE' => 'btn-transparent',
                    'BTN_SIZE' => false,
                    'BTN_TEXT' => Loc::getMessage('RX_BLOCK_17_1_DEMO_ELEMENT_BTN_TEXT'),
                    'BTN_LINK' => 'ranx_landing_form_order',
                    'BTN_LINK_TYPE' => 'form',
                ],
            ],
            [
                'NAME' => 'Year+',
                'PREVIEW_PICTURE' => '1.png',
                'PREVIEW_TEXT' => Loc::getMessage('RX_BLOCK_17_1_DEMO_ELEMENT_PREVIEW_TEXT'),
                'PREVIEW_TEXT_TYPE' => 'html',
                'TAB' => 2,
                'PROPERTY_VALUES' => [
                    'CHARS' => [
                        Loc::getMessage('RX_BLOCK_17_1_DEMO_ELEMENT_CHARS_1'),
                        Loc::getMessage('RX_BLOCK_17_1_DEMO_ELEMENT_CHARS_2'),
                        Loc::getMessage('RX_BLOCK_17_1_DEMO_ELEMENT_CHARS_3'),
                    ],
                    'PRICE' => '6000',
                    'DISCOUNT_PRICE' => '1000',
                    'BTN_SHOW' => 'Y',
                    'BTN_TYPE' => 'btn-transparent',
                    'BTN_SIZE' => false,
                    'BTN_TEXT' => Loc::getMessage('RX_BLOCK_17_1_DEMO_ELEMENT_BTN_TEXT'),
                    'BTN_LINK' => 'ranx_landing_form_order',
                    'BTN_LINK_TYPE' => 'form',
                ],
            ],
            [
                'NAME' => 'Year+',
                'PREVIEW_PICTURE' => '1.png',
                'PREVIEW_TEXT' => Loc::getMessage('RX_BLOCK_17_1_DEMO_ELEMENT_PREVIEW_TEXT'),
                'PREVIEW_TEXT_TYPE' => 'html',
                'TAB' => 3,
                'PROPERTY_VALUES' => [
                    'CHARS' => [
                        Loc::getMessage('RX_BLOCK_17_1_DEMO_ELEMENT_CHARS_1'),
                        Loc::getMessage('RX_BLOCK_17_1_DEMO_ELEMENT_CHARS_2'),
                        Loc::getMessage('RX_BLOCK_17_1_DEMO_ELEMENT_CHARS_3'),
                    ],
                    'PRICE' => '12000',
                    'DISCOUNT_PRICE' => '2000',
                    'BTN_SHOW' => 'Y',
                    'BTN_TYPE' => 'btn-transparent',
                    'BTN_SIZE' => false,
                    'BTN_TEXT' => Loc::getMessage('RX_BLOCK_17_1_DEMO_ELEMENT_BTN_TEXT'),
                    'BTN_LINK' => 'ranx_landing_form_order',
                    'BTN_LINK_TYPE' => 'form',
                ],
            ],
            [
                'NAME' => 'Optima+',
                'PREVIEW_PICTURE' => '1.png',
                'PREVIEW_TEXT' => Loc::getMessage('RX_BLOCK_17_1_DEMO_ELEMENT_PREVIEW_TEXT'),
                'PREVIEW_TEXT_TYPE' => 'html',
                'TAB' => 0,
                'PROPERTY_VALUES' => [
                    'CHARS' => [
                        Loc::getMessage('RX_BLOCK_17_1_DEMO_ELEMENT_CHARS_1'),
                        Loc::getMessage('RX_BLOCK_17_1_DEMO_ELEMENT_CHARS_2'),
                        Loc::getMessage('RX_BLOCK_17_1_DEMO_ELEMENT_CHARS_3'),
                    ],
                    'PRICE' => '1000',
                    'BTN_SHOW' => 'Y',
                    'BTN_TYPE' => 'btn-transparent',
                    'BTN_SIZE' => false,
                    'BTN_TEXT' => Loc::getMessage('RX_BLOCK_17_1_DEMO_ELEMENT_BTN_TEXT'),
                    'BTN_LINK' => 'ranx_landing_form_order',
                    'BTN_LINK_TYPE' => 'form',
                ],
            ],
            [
                'NAME' => 'Optima+',
                'PREVIEW_PICTURE' => '1.png',
                'PREVIEW_TEXT' => Loc::getMessage('RX_BLOCK_17_1_DEMO_ELEMENT_PREVIEW_TEXT'),
                'PREVIEW_TEXT_TYPE' => 'html',
                'TAB' => 1,
                'PROPERTY_VALUES' => [
                    'CHARS' => [
                        Loc::getMessage('RX_BLOCK_17_1_DEMO_ELEMENT_CHARS_1'),
                        Loc::getMessage('RX_BLOCK_17_1_DEMO_ELEMENT_CHARS_2'),
                        Loc::getMessage('RX_BLOCK_17_1_DEMO_ELEMENT_CHARS_3'),
                    ],
                    'PRICE' => '3000',
                    'DISCOUNT_PRICE' => '500',
                    'BTN_SHOW' => 'Y',
                    'BTN_TYPE' => 'btn-transparent',
                    'BTN_SIZE' => false,
                    'BTN_TEXT' => Loc::getMessage('RX_BLOCK_17_1_DEMO_ELEMENT_BTN_TEXT'),
                    'BTN_LINK' => 'ranx_landing_form_order',
                    'BTN_LINK_TYPE' => 'form',
                ],
            ],
            [
                'NAME' => 'Optima+',
                'PREVIEW_PICTURE' => '1.png',
                'PREVIEW_TEXT' => Loc::getMessage('RX_BLOCK_17_1_DEMO_ELEMENT_PREVIEW_TEXT'),
                'PREVIEW_TEXT_TYPE' => 'html',
                'TAB' => 2,
                'PROPERTY_VALUES' => [
                    'CHARS' => [
                        Loc::getMessage('RX_BLOCK_17_1_DEMO_ELEMENT_CHARS_1'),
                        Loc::getMessage('RX_BLOCK_17_1_DEMO_ELEMENT_CHARS_2'),
                        Loc::getMessage('RX_BLOCK_17_1_DEMO_ELEMENT_CHARS_3'),
                    ],
                    'PRICE' => '6000',
                    'DISCOUNT_PRICE' => '1000',
                    'BTN_SHOW' => 'Y',
                    'BTN_TYPE' => 'btn-transparent',
                    'BTN_SIZE' => false,
                    'BTN_TEXT' => Loc::getMessage('RX_BLOCK_17_1_DEMO_ELEMENT_BTN_TEXT'),
                    'BTN_LINK' => 'ranx_landing_form_order',
                    'BTN_LINK_TYPE' => 'form',
                ],
            ],
            [
                'NAME' => 'Optima+',
                'PREVIEW_PICTURE' => '1.png',
                'PREVIEW_TEXT' => Loc::getMessage('RX_BLOCK_17_1_DEMO_ELEMENT_PREVIEW_TEXT'),
                'PREVIEW_TEXT_TYPE' => 'html',
                'TAB' => 3,
                'PROPERTY_VALUES' => [
                    'CHARS' => [
                        Loc::getMessage('RX_BLOCK_17_1_DEMO_ELEMENT_CHARS_1'),
                        Loc::getMessage('RX_BLOCK_17_1_DEMO_ELEMENT_CHARS_2'),
                        Loc::getMessage('RX_BLOCK_17_1_DEMO_ELEMENT_CHARS_3'),
                    ],
                    'PRICE' => '12000',
                    'DISCOUNT_PRICE' => '2000',
                    'BTN_SHOW' => 'Y',
                    'BTN_TYPE' => 'btn-transparent',
                    'BTN_SIZE' => false,
                    'BTN_TEXT' => Loc::getMessage('RX_BLOCK_17_1_DEMO_ELEMENT_BTN_TEXT'),
                    'BTN_LINK' => 'ranx_landing_form_order',
                    'BTN_LINK_TYPE' => 'form',
                ],
            ],
            [
                'NAME' => 'Premium+',
                'PREVIEW_PICTURE' => '1.png',
                'PREVIEW_TEXT' => Loc::getMessage('RX_BLOCK_17_1_DEMO_ELEMENT_PREVIEW_TEXT'),
                'PREVIEW_TEXT_TYPE' => 'html',
                'TAB' => 0,
                'PROPERTY_VALUES' => [
                    'CHARS' => [
                        Loc::getMessage('RX_BLOCK_17_1_DEMO_ELEMENT_CHARS_1'),
                        Loc::getMessage('RX_BLOCK_17_1_DEMO_ELEMENT_CHARS_2'),
                        Loc::getMessage('RX_BLOCK_17_1_DEMO_ELEMENT_CHARS_3'),
                    ],
                    'PRICE' => '1000',
                    'BTN_SHOW' => 'Y',
                    'BTN_TYPE' => 'btn-transparent',
                    'BTN_SIZE' => false,
                    'BTN_TEXT' => Loc::getMessage('RX_BLOCK_17_1_DEMO_ELEMENT_BTN_TEXT'),
                    'BTN_LINK' => 'ranx_landing_form_order',
                    'BTN_LINK_TYPE' => 'form',
                ],
            ],
            [
                'NAME' => 'Premium+',
                'PREVIEW_PICTURE' => '1.png',
                'PREVIEW_TEXT' => Loc::getMessage('RX_BLOCK_17_1_DEMO_ELEMENT_PREVIEW_TEXT'),
                'PREVIEW_TEXT_TYPE' => 'html',
                'TAB' => 1,
                'PROPERTY_VALUES' => [
                    'CHARS' => [
                        Loc::getMessage('RX_BLOCK_17_1_DEMO_ELEMENT_CHARS_1'),
                        Loc::getMessage('RX_BLOCK_17_1_DEMO_ELEMENT_CHARS_2'),
                        Loc::getMessage('RX_BLOCK_17_1_DEMO_ELEMENT_CHARS_3'),
                    ],
                    'PRICE' => '3000',
                    'DISCOUNT_PRICE' => '500',
                    'BTN_SHOW' => 'Y',
                    'BTN_TYPE' => 'btn-transparent',
                    'BTN_SIZE' => false,
                    'BTN_TEXT' => Loc::getMessage('RX_BLOCK_17_1_DEMO_ELEMENT_BTN_TEXT'),
                    'BTN_LINK' => 'ranx_landing_form_order',
                    'BTN_LINK_TYPE' => 'form',
                ],
            ],
            [
                'NAME' => 'Premium+',
                'PREVIEW_PICTURE' => '1.png',
                'PREVIEW_TEXT' => Loc::getMessage('RX_BLOCK_17_1_DEMO_ELEMENT_PREVIEW_TEXT'),
                'PREVIEW_TEXT_TYPE' => 'html',
                'TAB' => 2,
                'PROPERTY_VALUES' => [
                    'CHARS' => [
                        Loc::getMessage('RX_BLOCK_17_1_DEMO_ELEMENT_CHARS_1'),
                        Loc::getMessage('RX_BLOCK_17_1_DEMO_ELEMENT_CHARS_2'),
                        Loc::getMessage('RX_BLOCK_17_1_DEMO_ELEMENT_CHARS_3'),
                    ],
                    'PRICE' => '6000',
                    'DISCOUNT_PRICE' => '1000',
                    'BTN_SHOW' => 'Y',
                    'BTN_TYPE' => 'btn-transparent',
                    'BTN_SIZE' => false,
                    'BTN_TEXT' => Loc::getMessage('RX_BLOCK_17_1_DEMO_ELEMENT_BTN_TEXT'),
                    'BTN_LINK' => 'ranx_landing_form_order',
                    'BTN_LINK_TYPE' => 'form',
                ],
            ],
            [
                'NAME' => 'Premium+',
                'PREVIEW_PICTURE' => '1.png',
                'PREVIEW_TEXT' => Loc::getMessage('RX_BLOCK_17_1_DEMO_ELEMENT_PREVIEW_TEXT'),
                'PREVIEW_TEXT_TYPE' => 'html',
                'TAB' => 3,
                'PROPERTY_VALUES' => [
                    'CHARS' => [
                        Loc::getMessage('RX_BLOCK_17_1_DEMO_ELEMENT_CHARS_1'),
                        Loc::getMessage('RX_BLOCK_17_1_DEMO_ELEMENT_CHARS_2'),
                        Loc::getMessage('RX_BLOCK_17_1_DEMO_ELEMENT_CHARS_3'),
                    ],
                    'PRICE' => '12000',
                    'DISCOUNT_PRICE' => '2000',
                    'BTN_SHOW' => 'Y',
                    'BTN_TYPE' => 'btn-transparent',
                    'BTN_SIZE' => false,
                    'BTN_TEXT' => Loc::getMessage('RX_BLOCK_17_1_DEMO_ELEMENT_BTN_TEXT'),
                    'BTN_LINK' => 'ranx_landing_form_order',
                    'BTN_LINK_TYPE' => 'form',
                ],
            ],
        ],
    ],
];
