<?php
if(!defined('B_PROLOG_INCLUDED') || B_PROLOG_INCLUDED !== true) die();

use Bitrix\Main\Localization\Loc;

return [
    '_EXCLUDE' => ['TEXT_COLOR'],
    '_INCLUDE' => ['INDENT_ELEMENTS', 'CONTENT_IMPORT', 'CONTENT_TABS'],
    'NAME' => Loc::getMessage('RX_BLOCK_19_1_NAME'),
    'COLS' => [2, 3, 4],
    'COLS_DEFAULT' => 4,
    'INDENT_TOP_DEFAULT' => 100,
    'INDENT_BOT_DEFAULT' => 100,
    'IMPORT_DATA_TYPE' => 'PRODUCTS',
    'SETTINGS' => [
        'HIDE_AVAILABLE' => [
            'TITLE' => Loc::getMessage('RX_BLOCK_19_1_SETTINGS_HIDE_AVAILABLE_TITLE'),
            'TYPE' => 'checkbox',
            'DEFAULT' => false,
        ],
        'USE_BASKET' => [
            'TITLE' => Loc::getMessage('RX_BLOCK_19_1_SETTINGS_USE_BASKET_TITLE'),
            'TYPE' => 'checkbox',
            'DEFAULT' => true,
        ],
    ],
    'ELEMENTS_FIELDS' => [
        'NAME',
        'PREVIEW_PICTURE',
        'PROPERTY_AVAILABLE',
        '_PRICE',
        '_LINK',
        'PROPERTY_MARKERS',
        '_POPUP',
        '_BTN',
    ],
    'POPUP_ELEMENTS_FIELDS' => [
        'PROPERTY_MORE_PHOTO',
        'PROPERTY_CAT',
        'PROPERTY_MARK',
        'PROPERTY_CHECK',
        'DETAIL_TEXT',
        'PROPERTY_CHARS',
    ],
    'FIELDS_MESS' => [
        'IMPORT_LINK_TYPE' => Loc::getMessage('RX_BLOCK_19_1_FIELDS_MESS_IMPORT_LINK_TYPE'),
    ],
    'ELEMENTS_FIELDS_MESS' => [
        'PROPERTY_CHECK' => Loc::getMessage('RX_BLOCK_19_1_ELEMENTS_FIELDS_MESS_PROPERTY_CHECK'),
        'DETAIL_TEXT' => Loc::getMessage('RX_BLOCK_19_1_ELEMENTS_FIELDS_MESS_DETAIL_TEXT'),
    ],
    'DEMO' => [
        'BLOCK' => [
            'NAME' => Loc::getMessage('RX_BLOCK_19_1_DEMO_BLOCK_NAME'),
            'PROPERTY_VALUES' => [
                'CATTITLE' => Loc::getMessage('RX_BLOCK_19_1_DEMO_BLOCK_CATTITLE'),
                'USE_TABS' => 'N',
            ],
        ],
        'ELEMENTS' => [
            [
                'NAME' => Loc::getMessage('RX_BLOCK_19_1_DEMO_ELEMENT_NAME'),
                'PREVIEW_PICTURE' => '1.png',
                'DETAIL_TEXT' => Loc::getMessage('RX_BLOCK_19_1_DEMO_ELEMENT_DETAIL_TEXT'),
                'PROPERTY_VALUES' => [
                    'AVAILABLE' => 'Y',
                    'PRICE' => '20000',
                    'CHARS' => [
                        Loc::getMessage('RX_BLOCK_19_1_DEMO_ELEMENT_CHARS_1'),
                        Loc::getMessage('RX_BLOCK_19_1_DEMO_ELEMENT_CHARS_2'),
                        Loc::getMessage('RX_BLOCK_19_1_DEMO_ELEMENT_CHARS_3'),
                        Loc::getMessage('RX_BLOCK_19_1_DEMO_ELEMENT_CHARS_4'),
                        Loc::getMessage('RX_BLOCK_19_1_DEMO_ELEMENT_CHARS_5'),
                    ],
                    'BTN_SHOW' => 'Y',
                    'BTN_TYPE' => 'btn-primary',
                    'BTN_SIZE' => 'btn-mr',
                    'BTN_TEXT' => Loc::getMessage('RX_BLOCK_19_1_DEMO_ELEMENT_BTN_TEXT'),
                    'BTN_LINK' => 'ranx_landing_form_order',
                    'BTN_LINK_TYPE' => 'form',
                    'POPUP_SHOW' => 'Y',
                    'CAT' => Loc::getMessage('RX_BLOCK_19_1_DEMO_ELEMENT_CAT'),
                    'MARK' => '4',
                    'MORE_PHOTO' => [
                        '2.png',
                        '3.png',
                        '2.png',
                    ],
                ],
            ],
            [
                'NAME' => Loc::getMessage('RX_BLOCK_19_1_DEMO_ELEMENT_NAME'),
                'PREVIEW_PICTURE' => '1.png',
                'DETAIL_TEXT' => Loc::getMessage('RX_BLOCK_19_1_DEMO_ELEMENT_DETAIL_TEXT'),
                'PROPERTY_VALUES' => [
                    'AVAILABLE' => 'Y',
                    'PRICE' => '20000',
                    'CHARS' => [
                        Loc::getMessage('RX_BLOCK_19_1_DEMO_ELEMENT_CHARS_1'),
                        Loc::getMessage('RX_BLOCK_19_1_DEMO_ELEMENT_CHARS_2'),
                        Loc::getMessage('RX_BLOCK_19_1_DEMO_ELEMENT_CHARS_3'),
                        Loc::getMessage('RX_BLOCK_19_1_DEMO_ELEMENT_CHARS_4'),
                        Loc::getMessage('RX_BLOCK_19_1_DEMO_ELEMENT_CHARS_5'),
                    ],
                    'BTN_SHOW' => 'Y',
                    'BTN_TYPE' => 'btn-primary',
                    'BTN_SIZE' => 'btn-mr',
                    'BTN_TEXT' => Loc::getMessage('RX_BLOCK_19_1_DEMO_ELEMENT_BTN_TEXT'),
                    'BTN_LINK' => 'ranx_landing_form_order',
                    'BTN_LINK_TYPE' => 'form',
                    'POPUP_SHOW' => 'Y',
                    'CAT' => Loc::getMessage('RX_BLOCK_19_1_DEMO_ELEMENT_CAT'),
                    'MARK' => '4',
                    'MORE_PHOTO' => [
                        '2.png',
                        '3.png',
                        '2.png',
                    ],
                ],
            ],
            [
                'NAME' => Loc::getMessage('RX_BLOCK_19_1_DEMO_ELEMENT_NAME'),
                'PREVIEW_PICTURE' => '1.png',
                'DETAIL_TEXT' => Loc::getMessage('RX_BLOCK_19_1_DEMO_ELEMENT_DETAIL_TEXT'),
                'PROPERTY_VALUES' => [
                    'AVAILABLE' => 'Y',
                    'PRICE' => '20000',
                    'CHARS' => [
                        Loc::getMessage('RX_BLOCK_19_1_DEMO_ELEMENT_CHARS_1'),
                        Loc::getMessage('RX_BLOCK_19_1_DEMO_ELEMENT_CHARS_2'),
                        Loc::getMessage('RX_BLOCK_19_1_DEMO_ELEMENT_CHARS_3'),
                        Loc::getMessage('RX_BLOCK_19_1_DEMO_ELEMENT_CHARS_4'),
                        Loc::getMessage('RX_BLOCK_19_1_DEMO_ELEMENT_CHARS_5'),
                    ],
                    'BTN_SHOW' => 'Y',
                    'BTN_TYPE' => 'btn-primary',
                    'BTN_SIZE' => 'btn-mr',
                    'BTN_TEXT' => Loc::getMessage('RX_BLOCK_19_1_DEMO_ELEMENT_BTN_TEXT'),
                    'BTN_LINK' => 'ranx_landing_form_order',
                    'BTN_LINK_TYPE' => 'form',
                    'POPUP_SHOW' => 'Y',
                    'CAT' => Loc::getMessage('RX_BLOCK_19_1_DEMO_ELEMENT_CAT'),
                    'MARK' => '4',
                    'MORE_PHOTO' => [
                        '2.png',
                        '3.png',
                        '2.png',
                    ],
                ],
            ],
            [
                'NAME' => Loc::getMessage('RX_BLOCK_19_1_DEMO_ELEMENT_NAME'),
                'PREVIEW_PICTURE' => '1.png',
                'DETAIL_TEXT' => Loc::getMessage('RX_BLOCK_19_1_DEMO_ELEMENT_DETAIL_TEXT'),
                'PROPERTY_VALUES' => [
                    'AVAILABLE' => 'Y',
                    'PRICE' => '20000',
                    'CHARS' => [
                        Loc::getMessage('RX_BLOCK_19_1_DEMO_ELEMENT_CHARS_1'),
                        Loc::getMessage('RX_BLOCK_19_1_DEMO_ELEMENT_CHARS_2'),
                        Loc::getMessage('RX_BLOCK_19_1_DEMO_ELEMENT_CHARS_3'),
                        Loc::getMessage('RX_BLOCK_19_1_DEMO_ELEMENT_CHARS_4'),
                        Loc::getMessage('RX_BLOCK_19_1_DEMO_ELEMENT_CHARS_5'),
                    ],
                    'BTN_SHOW' => 'Y',
                    'BTN_TYPE' => 'btn-primary',
                    'BTN_SIZE' => 'btn-mr',
                    'BTN_TEXT' => Loc::getMessage('RX_BLOCK_19_1_DEMO_ELEMENT_BTN_TEXT'),
                    'BTN_LINK' => 'ranx_landing_form_order',
                    'BTN_LINK_TYPE' => 'form',
                    'POPUP_SHOW' => 'Y',
                    'CAT' => Loc::getMessage('RX_BLOCK_19_1_DEMO_ELEMENT_CAT'),
                    'MARK' => '4',
                    'MORE_PHOTO' => [
                        '2.png',
                        '3.png',
                        '2.png',
                    ],
                ],
            ],
        ],
    ],
];
